-- USERS (renamed to app_users due to @Table annotation)
CREATE TABLE app_users
(
    username                   VARCHAR(255) PRIMARY KEY,
    password                   VARCHAR(255) NOT NULL,
    name                       VARCHAR(255),
    surname                    VARCHAR(255),
    role                       VARCHAR(50)  NOT NULL,
    is_account_non_expired     BOOLEAN DEFAULT TRUE,
    is_account_non_locked      BOOLEAN DEFAULT TRUE,
    is_credentials_non_expired BOOLEAN DEFAULT TRUE,
    is_enabled                 BOOLEAN DEFAULT TRUE
);

-- COUNTRIES
CREATE TABLE country
(
    id        bigint generated by default as identity PRIMARY KEY,
    name      VARCHAR(255) NOT NULL UNIQUE,
    continent VARCHAR(255)
);

-- HOSTS
CREATE TABLE host
(
    id            bigint generated by default as identity PRIMARY KEY,
    name          VARCHAR(255),
    surname       VARCHAR(255),
    country_id    bigint REFERENCES country (id) ON DELETE CASCADE,
    user_username VARCHAR(255) UNIQUE REFERENCES app_users (username) ON DELETE CASCADE
);

-- ACCOMMODATIONS
CREATE TABLE accommodation
(
    id        bigint generated by default as identity PRIMARY KEY,
    name      VARCHAR(255),
    category  VARCHAR(50),
    host_id   bigint REFERENCES host (id),
    num_rooms INTEGER,
    is_rented BOOLEAN DEFAULT FALSE
);

-- REVIEWS
CREATE TABLE review
(
    id               bigint generated by default as identity PRIMARY KEY,
    comment          TEXT,
    rating           INTEGER,
    accommodation_id bigint REFERENCES accommodation (id)
);

-- RESERVATIONS
CREATE TABLE reservation
(
    id                 bigint generated by default as identity PRIMARY KEY,
    user_username      VARCHAR(255) REFERENCES app_users (username),
    reservation_status VARCHAR(50)
);

-- RESERVATION_ACCOMMODATION (Join table for @ManyToMany)
CREATE TABLE reservation_accommodations
(
    reservation_id   bigint REFERENCES reservation (id),
    accommodation_id bigint REFERENCES accommodation (id),
    PRIMARY KEY (reservation_id, accommodation_id)
);

CREATE INDEX idx_reservation_user_username ON reservation(user_username);
CREATE INDEX idx_accommodation_host_id ON accommodation(host_id);
CREATE INDEX idx_review_accommodation_id ON review(accommodation_id);
CREATE INDEX idx_app_users_role ON app_users(role);